### ISSUE TITLE
bug d'affichage 

### ISSUE THREAD

**Issue by perdu101** [WoCha-FR/jeedom-linky#3]
D'abord un grand merci pour ce plugin!
Je remonte un bug.
Je me connecte au linky en local et en mode standard (en tri).
La valeur de SINSTS2 (Puissance app. instantanée soutirée phase 2) type info (normal donc) mais sous type autre (cela devrai être numérique) et changement non pris en compte par jeedom  (en essayant de forcer numérique) .
tout les autres Puissance app sont elle en numérique ...
Merci encore pour ce plugins

**Comment by WoCha-FR** [comment]
Bonsoir,
Je regarde cela très vite et pousse une nouvelle version au besoin.

**Comment by WoCha-FR** [comment]
Hello,
Je viens de pousser une béta avec la modification.
Il y avais bien une erreur dans la classe.
Merci de votre retour !

**Comment by WoCha-FR** [comment]
Mis à jour aussi en stable.
